import os
from dotenv import load_dotenv
import google.generativeai as genai

load_dotenv()

def get_gemini_insight(prompt: str) -> str:
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return "<div class='alert alert-warning'>GEMINI_API_KEY not set in .env</div>"
    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-2.0-flash")
        response = model.generate_content(prompt)
        # Robustly extract the text
        content = getattr(response, 'text', None)
        if not content:
            # Try extracting from candidates if present
            if hasattr(response, 'candidates') and response.candidates:
                content = response.candidates[0].content.parts[0].text
        if not content:
            return "<div class='alert alert-warning'>No insight generated by Gemini.</div>"
        return f"<div class='alert alert-info'>{content}</div>"
    except Exception as e:
        return f"<div class='alert alert-danger'>Gemini API error: {str(e)}</div>"
